name: Mi Primer Workflow hecho por m√≠ mismo

# trigger
on: push

jobs:
  primera_chamba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Mostrando y leyendo el README.md
        run: |
          echo "Mi primer github actions yo solito hola"
          ls -ltra
          cat README.md